language: android
android:
  components:
    - build-tools-19.1.0
    - extra-android-support
  licenses:
    - android-sdk-license-5be876d5
branches:
  only:
    - master
before_install:
  # Install 3rd-party dependencies
  # Module chat
  - mkdir chat/libs
  - cd chat/libs
  # aSmack 4.0.0
  - wget http://asmack.freakempire.de/4.0.0/asmack-android-8-4.0.0.jar
  # Done
  - cd ..
  # Done with the module
  - cd ..
  # Done with the 3rd-party dependencies
  # Fool CI system so that it thinks it has the files required to sign the APK, but they won't be used anyway
  - cd core
  - echo dumbAlias > lolin1.alias
  - echo dumbKeystore > lolin1gplaykey.keystore
  - echo dumbKeyPwd > lolin1key.pwd
  - echo dumbStoPwd > lolin1storage.pwd
  # Done
  - cd ..
script:
  - TERM=dumb gradle checkproductionDebug
