language: android
android:
  components:
    - build-tools-19.1.0
branches:
  only:
    - master
before_install:
  # Install 3rd-party dependencies
  - mkdir LoLChatAPI/libs
  - cd LoLChatAPI/libs
  # aSmack 4.0.0 RC2
  - wget http://asmack.freakempire.de/SNAPSHOTS/4.0.0-rc2-SNAPSHOT-2014-05-11/asmack-android-8-4.0.0-rc2-SNAPSHOT-2014-05-11.jar
  # Done
  - cd ..
  - cd ..
install:
  - true
script:
  - TERM=dumb gradle assemble
