language: android
android:
  components:
    - build-tools-19.1.0
  licenses:
    - android-sdk-license-5be876d5
branches:
  only:
    - master
before_install:
  # Install 3rd-party dependencies
  # Module chat
  - mkdir chat/libs
  - cd chat/libs
  # aSmack 4.0.0
  - wget http://asmack.freakempire.de/SNAPSHOTS/0.9.0-SNAPSHOT-2014-04-15/asmack-android-8-0.9.0-SNAPSHOT-2014-04-15.jar
  # Done
  - cd ..
  # Done with the module
  - cd ..
  # Done with the 3rd-party dependencies
  # Done
  - cd ..
